### ISSUE TITLE
`packages` option?

### ISSUE THREAD

**Issue by eitsupi** [mamba-org/devcontainer-features#7]
Can we add `packages` option to install any package, like https://github.com/rocker-org/devcontainer-features/tree/main/src/apt-packages?
For example, it may be useful to be able to use this Feature to install any version of Python.

**Comment by maresb** [comment]
Yes, sounds good to me. (Although in my mind, the ideal way to install packages is via a lockfile, so perhaps we should consider if we can support that as well.)

**Comment by eitsupi** [comment]
Thanks for reply. I agree with your point of view.

In order to send some kind of file into the container, I think we currently need a simple Dockerfile like the following.

```dockerfile
FROM foo
COPY filename /tmp/bar/
```

Perhaps an option to specify the path of the lock file in the container should reference this copied file (like `"lockFile": "/tmp/bar/filename"`).
This is an advanced option as it requires a Dockerfile, but I think it is worth adding.
