### ISSUE TITLE
Publish in the index

### ISSUE THREAD

**Issue by eitsupi** [mamba-org/devcontainer-features#8]
@maresb We have not received any replies from the mamba community, so I think it would be a good idea to release this Feature from outside mamba-org for now and add it to [the index](https://containers.dev/features).

https://github.com/eitsupi/mamba-devcontainer-features/pull/3#issuecomment-1351002960

Since the recent update (devcontainers/cli#346) allows us to indicate deprecated Features as deprecated, if the day comes when we can transfer this to mamba-org, we can deprecate the old Feature and direct them to the new one.

**Comment by maresb** [comment]
Yes, agreed. But let's re-ping @wolfv and @jonashaag and give them a day or two to respond. (They're incredibly busy, so our original request may have simply caught them at a bad time.) 

There is also some movement on their side regarding install scripts https://github.com/mamba-org/mamba/issues/2164#issuecomment-1359564081. I still hope that the various installation scripts (this, micro.mamba.pm, micromamba-docker, ansible-role-micromamba, etc.) can eventually converge somehow, but I think that will require some thought and work.

**Comment by wolfv** [comment]
hey! adding you to mamba-org now so you can move the repo if you want to :)

**Comment by wolfv** [comment]
@eitsupi you should've received an invitation to mamba-org which allows you to create public repos in there (and hopefully also to move this existign one)

**Comment by eitsupi** [comment]
@wolfv Thanks for the invitation!
I transferred this repo to mamba-org, so I will update some docs and add to the index!

**Comment by wolfv** [comment]
Awesome and sorry for being slow to reply! :)

**Comment by eitsupi** [comment]
I created a draft PR to add this repo to the index. (devcontainers/devcontainers.github.io#118)
After merging #9, I would like to release Feature and submit devcontainers/devcontainers.github.io#118.

I would be happy to have you review #9 and devcontainers/devcontainers.github.io#118.

**Comment by eitsupi** [comment]
Done🎉
![image](https://user-images.githubusercontent.com/50911393/210539477-f6d864b8-0f15-4ed8-80d9-ea0ffafbc3c9.png)
https://containers.dev/features

**Comment by wolfv** [comment]
Awesome, congrats!
